#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# theme
bspc config focused_border_color   "#c4a7e7"
bspc config active_border_color    "#c4a7e7"
bspc config normal_border_color    "#1f1d2e"
bspc config presel_feedback_color  "#9ccfd8"

bspc rule -a scrcpy state=floating
bspc rule -a Sign In - Google Accounts — Mozilla Firefox state=floating

# Bitwarden pop up
bspc rule -a "Chromium:crx_nngceckbapebfimnlniiiahkandclblb" state=floating

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Keyboard settings
setxkbmap us

# Wallpaper
xwallpaper --zoom $HOME/Pictures/$(cat $HOME/Pictures/.wallpaper) &

# Monitor
xrandr --output eDP1 --mode 1920x1080 --pos 0x1080 --rotate normal --output DP1 --off --output HDMI1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off

# Compositor
xcompmgr &

bspc config left_padding 34
eww -c $HOME/.config/bspwm/bspwm-bar --restart open bar-left &

ext=$(xinput list --id-only "/u/squeezeonein ortho5by12")
int=$(xinput list --id-only "AT Translated Set 2 keyboard")
[ -n "$ext" ] && setxkbmap -device "$ext" us
[ -n "$int" ] && setxkbmap -device "$int" ie -option caps:swapescape

xsetroot -cursor_name left_ptr

xrdb -merge ~/.Xresources
