#!/bin/sh

curr=$(bspc config left_padding)
if [ "$curr" -eq "34" ]; then
    bspc config left_padding 0
else
    bspc config left_padding 34
fi

eww open -c "$HOME/.config/bspwm/bspwm-bar/" --toggle bar-left
