#!/bin/sh

curr=$(bspc config left_padding)
if [ "$curr" -eq "36" ]; then
    bspc config left_padding 0
else
    bspc config left_padding 36
fi

$HOME/.local/bin/eww open -c "$HOME/.config/bspwm/bspwm-bar/" --toggle bar-left
